### ISSUE TITLE
ModuleNotFoundError: No module named 'naturalneighbor'

### ISSUE THREAD

**Issue by fnielsen** [DTUComputeCognitiveSystems/bayesian_cut#2]
A module seems to be missing from the requirements:

```python
>>> graph_cut_z_vector = BC.get_best_chain().max_log_lik_z_
>>> from bayesian_cut.utils import utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/bayesian_cut/utils/utils.py", line 13, in <module>
    import naturalneighbor
ModuleNotFoundError: No module named 'naturalneighbor'
>>> utils.Cluster_plot(BC)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'utils' is not defined
```

You have `naturalneighbor` in the `requirements.txt`, but it is not used in `setup.py` . You can read the `requirements.txt` in the `setup.py`, see https://github.com/fnielsen/scholia/blob/3d3a4559ec98be0a4baae622230c49f585d2d1f4/setup.py#L6

**Comment by fnielsen** [comment]
Ok, I see you have it in the `extras`.
